FROM eclipse-temurin:21-jdk AS build
WORKDIR /app
COPY . .
RUN ./mvnw -q -DskipTests package || (mvn -q -DskipTests package)

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/target/*products-service*.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java","-jar","/app/app.jar"]
